# Generated by Django 4.2.6 on 2023-10-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
