# Generated by Django 4.2.6 on 2023-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_displayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userWishlist',
        ),
        migrations.AddField(
            model_name='user',
            name='userWatchlist',
            field=models.ManyToManyField(related_name='watchlist', to='auctions.listings'),
        ),
    ]
