# Generated by Django 4.2.6 on 2023-10-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_winner_alter_listings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artAndCollectibles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artAndCollectibles', to='auctions.listings')),
                ('automotiveAndVehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automotiveAndVehicles', to='auctions.listings')),
                ('electronicsAndGadgets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronicsAndGadgets', to='auctions.listings')),
                ('homeAndGarden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeAndGarden', to='auctions.listings')),
                ('jewelryAndwatches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelryAndwatches', to='auctions.listings')),
            ],
        ),
    ]
