# Generated by Django 4.2.6 on 2023-10-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_category_alter_listings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='artAndCollectibles',
        ),
        migrations.RemoveField(
            model_name='category',
            name='automotiveAndVehicles',
        ),
        migrations.RemoveField(
            model_name='category',
            name='electronicsAndGadgets',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homeAndGarden',
        ),
        migrations.RemoveField(
            model_name='category',
            name='jewelryAndwatches',
        ),
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
    ]
