# Generated by Django 4.2.6 on 2023-10-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_category_listings_alter_listings_user_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
    ]
